### ISSUE TITLE
Set HTTP Server Timeouts

### ISSUE THREAD

**Issue by seanmalloy** [edgard/iperf3_exporter#2]
By default the web server from Go Lang's `net/http` package does not set timeouts.

https://github.com/edgard/iperf3_exporter/blob/master/iperf3_exporter.go#L221

You can set a proper timeout by doing something like this ...

```golang
srv := &http.Server{
    Addr:         "0.0.0.0:8080",
    ReadTimeout:  5 * time.Second,
    WriteTimeout: 5 * time.Second,
}
log.Fatal(srv.ListenAndServe())
```

**Comment by edgard** [comment]
Good catch. Closed with a8ec208
