### ISSUE TITLE
Specify Duration for Iperf test tor un

### ISSUE THREAD

**Issue by duganth** [edgard/iperf3_exporter#5]
I looked at the code (do not know Golang that well) and it looks like you have the ability to pass in var for iperf to run for different lengths; for example say I want to run each test for 60 seconds. I dont know if i'm missing how to pass it via CLI or Prometheus config or if its just a feature request. It would be very helpful if I could modify it with a parameter. Thanks!

**Comment by edgard** [comment]
You can pass any period you want with a param, check the README, an example has just been added to the "port" parameters, same goes for "period". It can be any go time.Duration formatted string.
